### ISSUE TITLE
Question about 3090 4-card training speed

### ISSUE THREAD

**Issue by xaswq** [csguoh/MambaIR#11]
Dear author,

I noticed the estimated training time for a 4-card 3090 setup is around 5 days for 5,000 iterations. Is this expected? I also found that using 1 card vs 4 cards both result in a 5 day estimate.

```
python -m torch.distributed.launch --nproc_per_node=4 --master_port=1234 basicsr/train.py -opt options/train/train_MambaIR_SR_x2.yml --launcher pytorch
```

Could you please advise if this training speed is normal? Any insights would be greatly appreciated.

![image](https://github.com/csguoh/MambaIR/assets/85377380/e4041c9b-6e36-4fec-8950-aeaf74dbffaf)

![image](https://github.com/csguoh/MambaIR/assets/85377380/d372aa17-3b38-4a24-bcbf-a55fb50e9313)

**Comment by csguoh** [comment]
Hi, since the training protocol of existing SR codebase uses training iteration instead of training epoch, therefore the estimated total training time is roughly similar between one GPU and four GPU. The main difference lies in the total batch size, i.e. when you use more GPUs, the total batch size is relatively larger so that the grad is more stable.

**Comment by xaswq** [comment]
Received. Noted with thanks!
