### ISSUE TITLE
About method comparison

### ISSUE THREAD

**Issue by 1001kathy** [csguoh/MambaIR#23]
hi，thanks for provide your pioneer work, I wonder have you compared the MambaIR with NAFNet? They are both a simple and linearity method. Looking forward your reply! ^_^

**Comment by csguoh** [comment]
Hi, thanks for you kind advice!
Due to the different task focuses of our approach and NAFNet, e.g., we mainly foucus image SR, Gaussian DN, JEPG CAR, while NAFNet focuses on deblurring, realDN, StereoSR, therefore, we did not compare with NAFNet due to the low overlap of the task types. If possible, we will consider adding these tasks to MambaIR in the future ;D
