### ISSUE TITLE
Params and Flops of MambaIRUNet.

### ISSUE THREAD

**Issue by Yaziwel** [csguoh/MambaIR#25]
I use thop to analyze the MambaIRUNet and the number of params is 25.92M. However, when I count the params using the following function, the params number is 31.50M:

`def count_parameters(model): 
  return sum(p.numel() for p in model.parameters() if p.requires_grad) ` 

Could you please exhibit the params and flops of MambaIRUNet?

**Comment by csguoh** [comment]
HI, thanks for your question.
As we discussed in [this issue](https://github.com/csguoh/MambaIR/issues/20#issuecomment-2054094217), the params and MACs calculated by the third-part library have a BUG. If you want to get the #param, you can use the function `count_parameters` you provided above. As for the MACs, since some operation in mamba is executed in cuda, which is ignored by `thop`, it can be a little bit hard to get the accurate number. You can refer the issue in original Mamba/VMamva repo to find a solution. And we will also try to solve it in the future. 
Let me know if you have any other questions ;)
